description: "Configuration file for the custom MNIST case"

global_settings:
  random_seed: &global_seed 42
  task_type: "classification"

dataset:
  type: "file"
  path:
    data: "data/mnist_784/images.npy"
    label: "data/mnist_784/label.npy"
  params: {}
  random_seed: *global_seed
  split:
    train_ratio: 0.8
    validation_ratio: 0.0
    test_ratio: 0.2
    shuffle: true
  features: null
  raw_preprocess_logic:
    module_name: "qxmt-tutorials.custom.raw_preprocess_logic"
    implement_name: "sampling_by_each_class"
    params:
        n_samples: 100
        labels: [0, 1]
  transform_logic:
    module_name: "qxmt-tutorials.custom.transform_logic"
    implement_name: "dimension_reduction_by_pca"
    params:
        n_components: 2

device:
  platform: "pennylane"
  name: "default.qubit"
  n_qubits: 2
  shots: null

feature_map:
  module_name: "qxmt-tutorials.custom.feature_map"
  implement_name: "CustomFeatureMap"
  params:
    reps: 2

kernel:
  module_name: "qxmt.kernels.pennylane"
  implement_name: "FidelityKernel"
  params: {}

model:
  name: "qsvc"
  file_name: "model.pkl"
  params:
    C: 1.0
    gamma: 0.05

evaluation:
  default_metrics: ["accuracy", "precision", "recall", "f1_score"]
  custom_metrics: [
    {"module_name": "qxmt-tutorials.custom.evaluation", "implement_name": "CustomMetric"}
    ]
